### ISSUE TITLE
nci_target: finish_frame receives unidentified value when writing NDEF

### ISSUE THREAD

**Issue by fredldotme** [mer-hybris/libnciplugin#11]
On Ubuntu Touch (64 bit, Volla Phone & Google Pixel 3a), when writing NDEF data to a tag using `ndef-write`, the `nci_target_transmit_finish_frame` function receives payload with a status value that is not defined by any constants (0x14).

As a workaround, for now we're letting this value pass through for writing NDEF data to succeed:
https://github.com/ubports/libnciplugin/commit/85f49a586c58712d4df822598cd0df80741338fe

This does seem like a problem though, hence this open issue. :)

**Comment by monich** [comment]
Please paste a detailed log which demonstrates the issue. I would like to see what's happening at the NCI level.

**Comment by monich** [comment]
Now that I've finally seen NCI 2.0 spec, this suddenly starts making sense. Values `0x11`..`0x17` are named `STATUS_OK_x_BIT` (where x is `1`..`7`) and those are not actually errors. That just indicates a Short Frame in NFC-A.

**Comment by monich** [comment]
I guess the issue has been resolved by e15329b
