### ISSUE TITLE
pkgconfig(nfcd-plugin) >= 1.0.40 is needed by libnciplugin-1.0.11-0.armv7hl

### ISSUE THREAD

**Issue by enesutku07** [mer-hybris/libnciplugin#8]
No provider of 'pkgconfig(nfcd-plugin) >= 1.0.40' found.
Setting version: 1.0.11
No journal files were found.
error: Failed build dependencies:
	pkgconfig(nfcd-plugin) >= 1.0.40 is needed by libnciplugin-1.0.11-0.armv7hl

**Comment by monich** [comment]
nfcd-plugin package is provided by https://git.sailfishos.org/mer-core/nfcd/

If nfcd 1.0.40 is required then it is really required. I usually don't bump dependencies without a good reason.
